# **Задание на повторение материала

[1. Задание](#cell1)  

[2. Задание](#cell2)  

[3. Задание](#cell3) 

[4. Задание](#cell4)

[5. Задание](#cell5) 

[6. Задание](#cell6)

[7. Задание](#cell7)

[8. Задание](#cell8)

[9. Задание](#cell9)

[10. Задание](#cell10)

[11. Задание](#cell11)

[12. Задание](#cell12)

[13. Задание](#cell13)


In [1]:
import numpy as np

##### <a id="cell1"></a>1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##### <a id="cell2"></a> 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### <a id="cell3"></a>3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


*  Для обозначения числа столбцов

In [11]:
b1 = a.reshape(6, -1)
b1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
b2 = a.reshape(3, -1)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
b3 = a.reshape(12, -1)
b3

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

*  Для обозначения числа строк

In [14]:
b4 = a.reshape(-1, 6)
b4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
b5 = a.reshape(-1, 3)
b5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

##### <a id="cell4"></a>4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Одномерный  массив -  это фиксированное количество элементов одного и того же типа, объединенных одним именем, где каждый элемент имеет свой номер. Фактически одномерный массив — это массив, у которого может быть только одна строка, и n-е количество столбцов. 

Массив, состоящий из одного столбца и 12 строк можно назвать двумерным массивом. 


##### <a id="cell5"></a>5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним,  равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [3]:
a = np.random.randn(3, 4)
a

array([[-0.10442654, -0.39814011,  0.95655567, -0.96815938],
       [-0.178641  ,  0.47499515, -0.47580306, -0.24578181],
       [ 0.23122708, -1.46561674, -1.09893942, -0.11613855]])

In [4]:
a.size

12

In [5]:
c = a.flatten()
c

array([-0.10442654, -0.39814011,  0.95655567, -0.96815938, -0.178641  ,
        0.47499515, -0.47580306, -0.24578181,  0.23122708, -1.46561674,
       -1.09893942, -0.11613855])

In [6]:
c.size

12

##### <a id="cell6"></a>6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [11]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


##### <a id="cell7"></a>7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [12]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [15]:
print(a.size)
print("Размерность a: {}".format(a.ndim))
print("Форма a: {}".format(a.shape))
print(b.size)
print("Размерность b: {}".format(b.ndim))
print("Форма b: {}".format(b.shape))

10
Размерность a: 1
Форма a: (10,)
10
Размерность b: 1
Форма b: (10,)


Разница между массивами a и b мной не обнаружена. (Замечено расхождение в написание кода.)

#####  <a id="cell8"></a>8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [28]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [29]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
v.size

10

#####  <a id="cell9"></a>9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [16]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [20]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [25]:
print("Размерность B: {}".format(B.ndim))

Размерность B: 2


In [27]:
B_inv = np.linalg.inv(B) 
B_inv

LinAlgError: Singular matrix

In [28]:
B_opr = np.linalg.det(B)
B_opr

0.0

Так как определитель матрицы В равен нулю, то обратной матрицы не существует.

#####  <a id="cell10"></a>10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [62]:
import random
random.seed(42)
print(random.random())

0.6394267984578837


In [63]:
a = random.seed(42)
print(a)

None


#####  <a id="cell11"></a>11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [44]:
c = np.random.randint(0, 16, (1, 16))
c

array([[15,  0, 13,  6,  7,  3,  3, 11,  5, 14,  3,  5,  5,  5, 13,  6]])

#####  <a id="cell12"></a>12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [45]:
C = c.reshape(4, 4)
C

array([[15,  0, 13,  6],
       [ 7,  3,  3, 11],
       [ 5, 14,  3,  5],
       [ 5,  5, 13,  6]])

In [46]:
B = 10 * C
B

array([[150,   0, 130,  60],
       [ 70,  30,  30, 110],
       [ 50, 140,  30,  50],
       [ 50,  50, 130,  60]])

In [47]:
D = C + B
D

array([[165,   0, 143,  66],
       [ 77,  33,  33, 121],
       [ 55, 154,  33,  55],
       [ 55,  55, 143,  66]])

In [48]:
D_opr = np.linalg.det(D)
D_opr

237477020.00000086

In [49]:
D_rank = np.linalg.matrix_rank(D)
D_rank

4

In [50]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00851362, -0.00131712,  0.00350297, -0.00901805],
       [-0.00115458, -0.00263423,  0.00700594,  0.00014572],
       [-0.00054366, -0.00344692, -0.00243807,  0.00889474],
       [-0.0049546 ,  0.01076113, -0.00347495,  0.00327318]])

#####  <a id="cell13"></a>13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [51]:
d = D_inv > 0
d

array([[ True, False,  True, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False,  True, False,  True]])

In [52]:
D_inv = d.astype(int)
D_inv

array([[1, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 1]])

In [59]:
E = np.where(D_inv, B, C)
E

array([[150,   0, 130,   6],
       [  7,   3,  30, 110],
       [  5,  14,   3,  50],
       [  5,  50,  13,  60]])